### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by piotrze** [nurkiewicz/polski-w-it#132]
Jak przetłumaczyć słowo workflow, aby to ładnie brzmiało?

**Comment by nurkiewicz** [comment]
Hmm, idea tego słownika jest taka, że jeśli nie istnieje oczywiste tłumaczenie, to nie szukamy go na siłę. *Ale* tutaj sugerowałbym _przepływ_ jako otwarcie dyskusji :-). 

* [synonimy](https://www.powerthesaurus.org/workflow)
* [Google Translate](https://translate.google.com/#view=home&op=translate&sl=en&tl=pl&text=workflow)

**Comment by pioorg** [comment]
Hej
Podoba mi się koncepcja "nic na siłę" i przy niej był został.
W temacie słowników to PONS tłymaczy _workflow_ jako _przepływ pracy_, jeśli dobrze czytam. Patrz: https://de.pons.com/%C3%BCbersetzung/englisch-polnisch/workflow
P.
