### ISSUE TITLE
Stworzyć i utrzymywać plik CSV z fiszkami w formacie akceptowalnym przez Anki SRS

### ISSUE THREAD

**Issue by danielpmichalski** [nurkiewicz/polski-w-it#151]
Powód: potrzeba efektywnego zapamiętania fraz bez zbędnych powtórek

Format pliku: https://docs.ankiweb.net/#/importing?id=text-files

**Comment by nurkiewicz** [comment]
Super pomysł! Znam, ale osobiście nie używam Anki. Wydaje się, że wystarczy prosty skrypt shellowy podpięty pod `pre-commit`. Jeśli jesteś chętny, z przyjemnością przygarnę PR :-).

**Comment by pioorg** [comment]
Ale czy to nie powinien być `skrypt powłoki`?  ;-)

**Comment by nurkiewicz** [comment]
:trollface: :-)
