### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by apokralipsa** [nurkiewicz/polski-w-it#208]
Szukam sensownego tłumaczenia dla "Refactor". W angielskim słowo może pełnić zarówno rolę czasownika jak i rzeczownika. Do głowy przychodzą mi tylko polskawe "refaktoryzować" (v) i "refaktoring" (n).

**Comment by Tomirad** [comment]
_faktoryzacja_ - rozkład na czynniki, wyrażenie ogólnie matematyczne.

Więc analogicznie będzie po prostu uproszczanie kodu. Tylko samo używanie słowa uproszczanie, jest zbytnim uproszczeniem procesu.

_refaktoryzacja_ może wpisać się do naszego słownika na stałe.
