### ISSUE TITLE
Contention

### ISSUE THREAD

**Issue by jandudulski** [nurkiewicz/polski-w-it#209]
Mam problem z tłumaczeniem `contention` - widziałem przynajmniej jako `rywalizacja` i `konkurencja`.

**Comment by Tomirad** [comment]
W jakich przypadkach to się pojawia? Jeżeli to starcie słowne to _polemika_ będzie dobrym słowem. Jeżeli to właśnie polegająca na rywalizacji, to może określenie _konfrontacja_ będzie poprawnie brzmieć?
