### ISSUE TITLE
Dodanie podziału na części mowy

### ISSUE THREAD

**Issue by kuc** [nurkiewicz/polski-w-it#24]
W języku angielskim często czasownik jest taki sam jak rzeczownik, ale przetłumaczenie ich na polski daje różne wyniki.
Np. "schedule" -> "zaplanować" lub "harmonogram"
Stąd sugerowałbym dodatkowe oznaczenia o którą część mowy chodzi w osobnej kolumnie, żeby łatwiej było to ujednoznaczniać. Póki co widzę że tylko "setup" jest umieszczony w taki sposób, a i tak brakuje mu kilku tłumaczeń (skonfigurować, zainstalować).

Alternatywnie w kolumnie "polski" zrobić jakiś standardowy podział, coś na wzór jak np. stosowany tutaj w sekcji "znaczenia": https://pl.wiktionary.org/wiki/schedule

**Comment by nurkiewicz** [comment]
Tam, gdzie ma to sens, dodałem skróty _v_ (_verb_) czy _n_ (_noun_).
