### ISSUE TITLE
roadmap -> harmonogram

### ISSUE THREAD

**Issue by tarsa** [nurkiewicz/polski-w-it#40]
Kalekie tłumaczenie "roadmap" to "mapa drogowa" i można go zobaczyć w dużych ilościach wpisując w Google frazy typu "mapa drogowa intel".

**Comment by nurkiewicz** [comment]
Bardzo słuszna uwaga. Tylko nie jestem pewien tłumaczenie, bo harmonogram sugeruje ramy czasowe, a "roadmapa" chyba takowych mieć nie musi. Np. "2.0 roadmap" to raczej zbiór pomysłów i założeń niż konkretny harmonogram.

**Comment by tarsa** [comment]
Faktycznie. Chyba zasugerowałem się tym, że (prawie?) zawsze jak widziałem określenie roadmap to cele były powstawiane w ramy czasowe, np konkretny rok albo konkretny kwartał. W tych przypadkach (czyli w przeważającej części ogółu przypadków) termin harmonogram oddawałby sens oryginału. W pozostałych można użyć słowa "plan".

**Comment by bartekbrak** [comment]
Nieśmiało proponuję "plan", "plan prac".

**Comment by nurkiewicz** [comment]
Brzmi spoko, zrobisz PR? W środkowej kolumnie daj "mapa drogowa" :-)
