### ISSUE TITLE
Tłumaczenie słowa expire - wygasnąć / wygasać, nie wygasić.

### ISSUE THREAD

**Issue by lukaszkomar93** [nurkiewicz/polski-w-it#44]

**Comment by nurkiewicz** [comment]
Ciekawostka: *expire* [może też znaczyć](https://english.stackexchange.com/questions/55146/expired-or-passed-away) *umierać* :-). Fajne słowo, zrobisz PR?

**Comment by lukaszkomar93** [comment]
Może, angielski ma dużo ciekawych synonimów :). Jak jednak słusznie wcześniej pisałeś w kilku miejscach, starałem się trzymać stricte naszego żargonu informatycznego, więc pierwsze co oczywiście przyszło mi do głowy do czego może nawiązywać to słowo, to _tokens_. Zrobię, pozdro :+1:
