### ISSUE TITLE
Zautomatyzować sprawdzanie słów użytych w propozycjach zmian przy pomocy słowników internetowych i wikipedii

### ISSUE THREAD

**Issue by ArturGajowy** [nurkiewicz/polski-w-it#6]
Motywacja: https://github.com/nurkiewicz/polski-w-it/pull/3

😉

**Comment by nurkiewicz** [comment]
Ciekawe, teoretycznie dałoby się to oskryptować Travisem i Pythonem... Jeśli problem będzie się nasilał, pomyślę :-).

**Comment by nurkiewicz** [comment]
Położyłem pewne podwalimy w https://github.com/nurkiewicz/polski-w-it/commit/7926d6c26949f4561a8afa81240fa5cce6704e28 (mój pierwszy test w pytest), możesz śmiało kontynuować :-)

**Comment by nurkiewicz** [comment]
Położyłem pewne podwalimy w https://github.com/nurkiewicz/polski-w-it/commit/7926d6c26949f4561a8afa81240fa5cce6704e28 (mój pierwszy test w pytest), możesz śmiało kontynuować :-)

**Comment by ArturGajowy** [comment]
Świetny pomysł z walidacjami struktury! Jeśli mogę coś zasugerować - sprawdzenia w słownikach nie robiłbym na zasadzie "nie ma - test czerwony". Raczej po każdej zmianie robiłbym komentarz w danym PR z linkami do definicji wszystkich słów dodanych/zmienionych w danym PR (polskie sprawdzane w polskich źródłach, angielskie - w angielskich)
