### ISSUE TITLE
Dodanie nowego słowa do zbioru - escape

### ISSUE THREAD

**Issue by maciek1839** [nurkiewicz/polski-w-it#62]
Dużo osób używa tego słowa i mówi o czynności "eskejpować". Sam nie potrafię znaleźć dobrego tłumaczenie jak i również w internecie nie spotkałem definicji dla jezyka polskiego jeśli chodzi o operację "eskejpować".

**Comment by piecioshka** [comment]
Moje propozycje: `Wyjdź`, `Opuść`

**Comment by MaciekKuna** [comment]
Doprecyzowując, mam na myśli użycie tego "escape" w kontekście np. "escape character". Tłumacząc na polski taką operację przy użyciu twojej propozycji @piecioshka - "opuszczenie znaku" / "usunięcie znaku" wydaje się poprawne, racja?

**Comment by piecioshka** [comment]
Aaa, to się nie zrozumieliśmy :) 

W tym kontekście, to `opuszczenie znaku` jest bezsensowne :/
