### ISSUE TITLE
Błędne tłumaczenie słowa "feature"

### ISSUE THREAD

**Issue by panicz** [nurkiewicz/polski-w-it#7]
Jakkolwiek inicjatywa jest za wszechmiar chwalebna, słowniczek wydaje się przemilczać kwestię istnienia słów, które nie mają swoich odpowiedników w języku polskim.
Jednym z takich słów jest słowo "feature", które autorzy próbują tłumaczyć jako słowo "funkcja".
Problemów z takim przekładem jest kilka. Po pierwsze, słowu "funkcja" odpowiada - zasadniczo jeden do jednego - angielskie słowo "function", którego nie można stosować zamiennie ze słowem "feature" (i które w kontekście IT posiada już i tak zbyt wiele znaczeń).
Po drugie, innym odpowiednikiem słowa "feature" używanym niekiedy w literaturze polskiej, jest słowo "cecha" (na przykład określenie "feature extraction" tłumaczy się niekiedy jako "ekstrakcja cech"). W języku angielskim nie są to dwa odrębne znaczenia.

Być może najbliższym znaczeniowo słowem w języku polskim, odpowiadającym angielskiemu "feature", byłoby słowo "wyróżnik", mimo że żaden ze słowników, z których korzystam, nie odnotowuje tego faktu, być może z powodu braku związków etymologicznych. (Jednak ja nie mam problemu, żeby czasem powiedzieć po prostu "ficzer")

**Comment by hexmind** [comment]
temat nie jest banalny, ale to _funkcja_ jest właściwym tłumaczeniem
https://sjp.pwn.pl/slowniki/funkcjonalno%C5%9B%C4%87.html
https://sjp.pwn.pl/sjp/homonimia;2560759.html

**Comment by panicz** [comment]
na jakiej podstawie tak twierdzisz?

**Comment by hexmind** [comment]
Podałem źródła. 
Cecha - spotykane tylko w literaturze, funkcjonalność - inne znaczenie.

**Comment by panicz** [comment]
Podałeś odniesienie do słowa "funkcjonalność", ale jako właściwe tłumaczenie przedstawiłeś słowo "funkcja"

**Comment by hexmind** [comment]
@panicz, są tam poniższe linki:
https://sjp.pwn.pl/poradnia/haslo/funkcjonalnosc;7526.html
https://sjp.pwn.pl/poradnia/haslo/Funkcja-a-funkcjonalnosc;17099.html
https://sjp.pwn.pl/poradnia/haslo/Funkcja-a-funkcjonalnosc;18108.html

**Comment by panicz** [comment]
Tamże:
"Oczywiście, rozróżnienie na funkcję i funkcjonalność w języku specjalistycznym nie wzięło się znikąd – w świecie IT czym innym jest funkcja, a czym innym funkcjonalność."

**Comment by hexmind** [comment]
Owszem, ale w żargonie. Wystarczy istniejące słowo funkcja, mimo, że może się nie podobać ze względu na wieloznaczność i szersze znaczenie.

**Comment by tomekc** [comment]
Widzę, że to palący problem, który nie tylko mnie nie daje spokoju :)

Fukcja, za [SJP](https://sjp.pl/funkcja) jest chyba dobrym wyborem:

_Funkcja_
...
3. możliwość wykonania czegoś przez urządzenie lub program komputerowy;

**Comment by panicz** [comment]
Rzecz w tym, że żaden wybór nie jest dobry.
ikonka z awatarem albo ładne logo też mogą być nazwane "ficzerami", mimo że żadne z nich nie jest "możliwością wykonania czegoś przez urządzenie lub program komputerowy".
Nie wiem zresztą, jakim sposobem odwoływanie sie do słownika języka polskiego miałoby tutaj być pomocne, skoro chodzi o znalezienie adekwatnego przekładu. Można sobie sprawdzić w słowniku angielsko-polskim:
https://ling.pl/slownik/angielsko-polski/feature
Owszem, znajduje się tam słowo "funkcja" (z zaznaczeniem że chodzi o kontekst techniczny), ale przede wszystkim są tam takie znaczenia jak "cecha, rys, właściwość", w użyciu czasownikowym "cechować/znamionować coś, stanowić cechę czegoś, wyróżniać się czymś".
Możemy też zajrzeć do słownika synonimów
http://www.thesaurus.com/browse/feature
żeby przekonać się, że wśród wyrazów bliskoznacznych słowo "function" czy "functionality" nie występuje, nawet na dalekiej pozycji

**Comment by tomekc** [comment]
To są właśnie bóle tłumaczy. Tłumaczenia są jak kobiety: wierne nie są piękne, piękne nie są wierne :)

**Feature** jest bezpośrednio nieprzetłumaczalne, bo anglojęzyczni rozumieją to przez "_a distinctive attribute or aspect of something_". Nowa funkcja programu komputerowego, chyba pasuje pod tą definicję?. 
Nowa ikonka lub logo jako _feature_? Być może. W praktyce troche naciągane - pracuję od lat z anglojęzycznymi PM-ami, i nazwaliby to raczej kosmetyczną poprawką, _delightem_.

_Feature - funkcja_ nie jest idealnym przełożeniem, ale moim zdaniem wciąż bardzo dobrym przybliżeniem - w 80% będzie adekwatne.

**Comment by panicz** [comment]
Z semantycznego punktu widzenia lepszym słowem od słowa "funkcja" będzie "wyróżnik", ale ono istotnie nie odpowiada temu, w jaki sposób to słowo funkcjonuje w światku IT.
Prawdopodobnie chęć tłumaczenia słowa "feature" jako "funkcjonalność" czy "funkcja" bierze się z odmienności perspektywy. Słowo "feature" ma raczej charakter sprzedażowy, a słowo "funkcjonalność" -- implementacyjny. Developerzy nie dodają "nowych wyróżników" do aplikacji, tylko istotnie dodają "nowe funkcjonalności".
To, co dla zleceniodawcy jest "wyróżnikiem, mającym zwiększyć sprzedawalność aplikacji", dla developera jest "funkcjonalnością do dodania". Prawdopodobnie ta różnica percepcji jest związana z tym, że jesteśmy plantacją outsourcingową, i w ogóle nie jesteśmy uczeni zwracać uwagę na ten pierwszy aspekt.

Ale właśnie z tego powodu protestuję przeciwko tłumaczeniu "feature" jako "funkcja". (Czy moje protesty będą słyszane, to inna kwestia)

Przy okazji może też warto się zastanowić, co zrobić ze słowem "developer" :)

**Comment by panicz** [comment]
Być może najlepszym odpowiednikiem angielskiego "feature" byłoby zapożyczone co prawda z jidysz, ale dobrze w polszczyźnie utarte słowo "cymes"? :)

**Comment by nlhnt** [comment]
Dzień dobry, przepraszam za odgrzewanie starego wątku, ale słowo funkcja ma się nijak do słowa feature.
Znacznie lepszym tłumaczeniem jest wspomniany wyróżnik lub cecha.
Dlaczego tak uważam
Weźmy na tapetę `feature extractors` z dziedziny ML (ang machine learning) oraz SL (ang. statistical learning). W tej dziedzinie "IT" ekstrakcja funkcji jest conajmniej zabawna, słowo funkcja i function w języku polskim i angielskim oznaczają w matematyce przekształcenie wejścia X na wyjście Y (X -> Y), które oznaczamy inaczej Y=f(X). W dziedzinie ML/SL jesteśmy często, przynajmniej w przypadku uczenia nadzorowanego, zainteresowani odnalezieniem estymatora lub aproksymacji funkcji f(X), który zazwyczaj opisywany jest f_hat. W takich scenariuszach ekstraktory wyróżników/cech tensorów/wektorów wejściowych X są odpowiedzialne za wydobycie cech/wyróżników które są charakterystyczne dla danych obserwacji Xi. Nie wydobywamy z tych danych "funkcji", wydobycie funkcji jest równoważne stworzeniu modelu statystycznego, który właśnie pewne przekształcenie X -> Y stara się modelować...

**Comment by hexmind** [comment]
Cześć,
jak słusznie zauważyłeś słowo _feature_ jest [homonimem](https://sjp.pwn.pl/slowniki/homonim), stąd różne znaczenia, zależnie od kontekstu. Najczęściej (w oprogramowaniu) jest to funkcja ale już w_ML_ raczej cecha (ekstrakcja). 
Najważniejsze, żeby wiedzieć że funkcjonalność ma inne znaczenie niż _feature_ i brak liczby mnogiej.
Temat jest stary i zamknięty więc nie będę już odpisywał.

PS https://sjp.pwn.pl/poradnia/haslo/na-tapet-czy-na-tapete;15076.html

**Comment by nurkiewicz** [comment]
@nlhnt nie widzę powodu, dla którego homonimy nie mogłyby się także znaleźć w słowniku, czyli

```feature -> funkcja, cecha```

czy wręcz

```feature -> funkcja (w zdaniu "implementing a new feature"), cecha (w zdaniu "feature extraction")```
