### ISSUE TITLE
footprint

### ISSUE THREAD

**Issue by nurkiewicz** [nurkiewicz/polski-w-it#76]
Szukam dobrego tłumaczenia słowa _footprint_. Technicznie to jest [zajętość przestrzeni](https://www.computerhope.com/jargon/f/footprin.htm), czyli nie do końca np. _narzut_

**Comment by pioorg** [comment]
Może coś w rodzaju "ślad" lub "odcisk"? Wiem, że _carbon footprint_ (czyli ślad węglowy) to nie to samo, ale szlak przetarty. Co ciekawe, Niemcy nie zawsze tłumaczą: [https://de.pons.com/%C3%BCbersetzung?q=footprint&l=deen&in=&lf=en&qnac=](punkt 3.)
