### ISSUE TITLE
Disable/Enable

### ISSUE THREAD

**Issue by imclick** [nurkiewicz/polski-w-it#79]
Dodanie nowych słów do słownika - enable oraz disable

disable - disejblować -  blokować/zablokować
enable - enejblować - odblokować

**Comment by pioorg** [comment]
Słuszna koncepcja, brakuje tego. ;-)
Przy czym szedłbym w formy niedokonane: uaktywniać i wyłączać/(za)blokować, bazując na: https://de.pons.com/%C3%BCbersetzung?q=enable&l=enpl&in=&lf=en&qnac= oraz https://de.pons.com/%C3%BCbersetzung?q=disable&l=enpl&in=&lf=en&qnac=.
Odblokować bardziej widzę jako "unlock"... Słowniki Ponsa i PWN są zgodne w kwestii enable, w obu jest "uaktywnić/uaktywniać".
